variable "scalr_aws_secret_key" {}
variable "scalr_aws_access_key" {}
variable "aws_region" {}
variable "vpc_name" {}
variable "eks_cluster_name" {}
variable "kubernetes_version" {}
variable "configure_kubectl" {}
variable "kubectl_config_path" {}
variable "configure_openid_connect_provider" {}
variable "endpoint_public_access" {}
variable "eks_worker_keypair_name" {
